template_path: application.yaml
parameters:
  InstanceType: {{ var.instance_type }}
  KeyName: {{ var.key_pair_name }}
  ServiceName: {{ var.service_name }}
  ImageId: {{ var.image_id }}
  VolumeSize: "{{ var.volume_size }}"
