#!/bin/bash

# This is an example file for creating and running a pyenv virtual
# environment. It is only meant to be a guide which you can take from.
# Large changes in third party libraries or other unforeseen
# issues could cause this file to become stale. If this example begins
# to fail, consider checking
# https://github.com/tophatmonocle/service-infrastructure/blob/master/script/bootstrap
# or elsewhere in the repository for updates.
# If updating this file, also update it in the be-library-template repo.

# Based on conventions from https://github.com/github/scripts-to-rule-them-all
# script/bootstrap: Resolve all dependencies that the application requires to
# run.

# If not in CI, we have to install the correct python versions
if [[ -z $CI ]]; then
    cat .python-version | xargs -n1 pyenv install -s
else
    if [[ ! -f `pwd`/.python-version ]]; then
        echo "You are missing a .python-version file."
        echo "pyenv will give you bizarre errors without this!"
        echo "You need to create this file to continue."
        return
    fi
fi

VENV="${PWD##*/}.venv"
test -d $VENV || python3 -m venv $VENV || return
$VENV/bin/pip install -U pip --no-cache-dir
$VENV/bin/pip install -e ".[dev]"

. $VENV/bin/activate
