name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
        pip install -e .
    - name: Check auto-formatted
      run: |
        black --check src tests
    - name: Lint with flake8
      run: |
        # Black uses max length of 88
        flake8 src tests --max-line-length 88 --statistics --show-source
    - name: Test with pytest
      run: |
        pytest
